# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e42a829648e62e4efcfaf27cdb4422b91bb992adb07ab8f92f30435f32ae75d48dba7779c69dc53bfc8a765c7919c7a5887022c9af0eb38bf1e2a41b4cfd218

test:
  secret_key_base: 34add904720fc00a4549465dc7383ad17d0fbe85c66eb114aa03706adcddc92b28cd986f66567302d8e4eb2a71b9f54a332e26d0bcc6a6e25028d10ed92bfcc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
